export CPU_COUNT := `nproc --all`

mod:
    go mod tidy
    go mod download

gen:
    go generate ./...

lint:
    modernize ./...
    golangci-lint run ./...

lint-fix:
    modernize --fix ./...
    golangci-lint run --fix ./...
    nix fmt

test-ci:
    go test -race -parallel={{CPU_COUNT}} -timeout=90s -cover ./...

test:
    go test -race -count=1 -parallel={{CPU_COUNT}} -timeout=90s -cover ./...
